PARAMS_FILE = "params.json"
INPUT_PATH = "input"
ACCEPTED_FILE_EXTENSIONS = ["wav"]

RESULT_CSV_FILENAME = "analysis_results.csv"


KNN_NEIGHBOUR_COUNT = 5
KNN_TEST_SPLIT = 0.2
KNN_RANDOM_STATE = 69
KNN_CROSS_VALIDATION_COUNT = 5
